Feature/equity_index
arup-group/social-data pull request #18
Opened 2021-11-24 22:31 UTC by shanenak

Equity Explorer and Transportation Index

2021-11-29 16:35 UTC, jstock29 commented on equity_explorer.py
> +    st.write('')
We can deal with line breaks in markdown. Just add this fomatting in a single st.write()

2021-11-29 16:37 UTC, jstock29 commented on equity_explorer.py
> +            radio_data = st.radio('Filter map for:', ('Equity Geos', 'All census tracts'),key='equity')
Equity geos is a bit ambiguous. What does this mean?

2021-11-29 16:38 UTC, jstock29 commented on equity_explorer.py
> +            transport_df = transport_df.loc[:, ~transport_df.columns.duplicated()]
Minor comment: we can see this line is duplicated in each if, so it can be moved outside and and be done once

2021-11-29 16:54 UTC, jstock29 commented on equity_explorer.py
> +        visualization.make_horizontal_bar_chart(averages, epc_averages, feature)
Potential use case for lighter-weight st.metric component?

2021-11-29 17:15 UTC, jstock29 requested changes
Some general comments as well as very specific things. One general thing would be to take a little time and clean up hanging comments, check variable types, do some autoformatting, etc. Also, need to add documentation in README.md and in the app code for users

2021-11-29 17:15 UTC, jstock29 commented on visualization.py
> +text = HTML(value='Move the viewport')
What is this? it's outside of a function scope

2021-11-29 17:15 UTC, jstock29 commented on visualization.py
> +def filter_by_viewport(widget_instance, payload):
Unclear what the usage of this is and it's got some undefined variable issues. df doesn't exist as defined in the arguments, and it seems like it's passed as a callback from the onclick of the map. Not sure what the functionality is meant to be and how it's meant to work

2021-11-29 17:15 UTC, jstock29 commented on visualization.py
> +    EQUITY_MAP_HEADERS = [map_feature] + [x + '_check' for x in queries.EQUITY_CENSUS_POC_LOW_INCOME] + [x + '_check' for x in queries.EQUITY_CENSUS_REMAINING_HEADERS]
typically limit ALLCAPS to global variables in Python

2021-11-29 17:15 UTC, jstock29 commented on visualization.py
> +    NTM_shapes = gpd.read_file('NTM_shapes.json')
Known todo: need to update to database table

2021-11-29 17:15 UTC, jstock29 commented on visualization.py
> +    if len(geo_df_copy['coordinates'][0][0][0]) > 0:
Default zoom in my tests was very zoomed in. I just selected the state of Alabama and the views were of a cluster of tracts instead of the state.

2021-11-29 17:15 UTC, jstock29 commented on equity_explorer.py
> +                st.write("More details to come! Read [here](" +queries.LINKS['mtc_framework']+ ") for more info")
lol we'll need to fill this in before merging but flagging now

2021-11-29 17:15 UTC, jstock29 commented on equity_explorer.py
> +        df = queries.clean_equity_data(df)
this is very useful cleaning that would be good to do earlier so that it's available in the raw data output

2021-11-29 17:15 UTC, jstock29 commented on queries.py
> +LINKS = {'mtc_framework': 'https://bayareametro.github.io/Spatial-Analysis-Mapping-Projects/Project-Documentation/Equity-Priority-Communities/#summary-of-mtc-epc-demographic-factors--demographic-fact
This should probably go in constants.py since it's not related to the queries

2021-11-29 17:15 UTC, jstock29 commented on run.py
>              The Equity Index is a set of Arup-designed analysis to show access to transit and other equity indicators at the census tract level.
Flagging for you to add more detail and documentation here and elsewhere

2021-11-29 22:14 UTC, shanenak commented on ex.html
> +<!DOCTYPE html>
I think I used it for a test a while back. I'll delete it now.

2021-11-30 19:51 UTC, shanenak commented on equity_explorer.py
> +    st.write('')
Updated and committed, thanks for pointing this out.

2021-11-30 19:52 UTC, shanenak commented on equity_explorer.py
> +        df = queries.clean_equity_data(df)
Agreed, I've moved it to immediately follow the other lines with cleaning

2021-11-30 19:59 UTC, shanenak commented on equity_explorer.py
> +            radio_data = st.radio('Filter map for:', ('Equity Geos', 'All census tracts'),key='equity')
Agreed, I was having trouble with formatting, so I tried to abbreviate. I've updated the formatting and made it more descriptive.

2021-11-30 21:10 UTC, shanenak commented on equity_explorer.py
> +            transport_df = transport_df.loc[:, ~transport_df.columns.duplicated()]
Agreed, changed.

2021-11-30 21:19 UTC, shanenak commented on equity_explorer.py
> +        visualization.make_horizontal_bar_chart(averages, epc_averages, feature)
Not sure, perhaps we can discuss this next time.

2021-11-30 23:14 UTC, shanenak commented on queries.py
> +LINKS = {'mtc_framework': 'https://bayareametro.github.io/Spatial-Analysis-Mapping-Projects/Project-Documentation/Equity-Priority-Communities/#summary-of-mtc-epc-demographic-factors--demographic-fact
Updated

2021-12-01 00:08 UTC, shanenak commented on queries.py
> +def minmax_norm(data: pd.DataFrame):
Yes, you are correct, thank you.

2021-12-01 00:11 UTC, shanenak commented on queries.py
> +def get_county_level_data (df: pd.DataFrame) -> pd.DataFrame:
Can we discuss this as well? I don't actually use this method, so I could probably just delete?

2021-12-01 00:15 UTC, shanenak commented on visualization.py
> +from fpdf import FPDF
Yes, downloading as PDF was a priority for Sophia, but it ended up being too big a task for this iteration. Commented out all code related to downloading as PDF.

2021-12-01 00:18 UTC, shanenak commented on visualization.py
> +text = HTML(value='Move the viewport')
oh I thought you wrote that. The variable "text" is referenced in filter_by_viewport, so I just moved it.

2021-12-01 00:21 UTC, shanenak commented on visualization.py
> +def filter_by_viewport(widget_instance, payload):
Apologies, I completely forgot that I had pasted that from somewhere. I did it so long ago that I thought you were the one that wrote it. I just deleted the functions.

2021-12-01 00:21 UTC, shanenak commented on visualization.py
> +text = HTML(value='Move the viewport')
Deleted per the next comment.

2021-12-01 00:22 UTC, shanenak commented on visualization.py
> +    EQUITY_MAP_HEADERS = [map_feature] + [x + '_check' for x in queries.EQUITY_CENSUS_POC_LOW_INCOME] + [x + '_check' for x in queries.EQUITY_CENSUS_REMAINING_HEADERS]
good to know, updated.

2021-12-01 00:23 UTC, shanenak commented on equity_explorer.py
> +                st.write("More details to come! Read [here](" +queries.LINKS['mtc_framework']+ ") for more info")
Added more details.

2021-12-01 00:26 UTC, shanenak commented on run.py
>              The Equity Index is a set of Arup-designed analysis to show access to transit and other equity indicators at the census tract level.
Updated on this page

2021-12-01 14:57 UTC, jstock29 commented on constants.py
> +| Feature Name | Resolution | Source | Updated | Notes |
This is great, can you add to the readme as well in the same table as the other datasets?

2021-12-01 14:59 UTC, jstock29 commented on equity_explorer.py
> +from constants import STATES as STATES, EQUITY_DATA_TABLE as EQUITY_DATA_TABLE, TRANSPORT_DATA_TABLE as TRANSPORT_DATA_TABLE, LINKS as LINKS
I don't think the as syntax is necessary here

2021-12-01 15:02 UTC, jstock29 commented on queries.py
> +    data.rename({'below_pov_level': 'Below Poverty Level'}, axis=1, inplace=True)
These sorts of renaming can be done in a single statement with multiple key-value mappings

2021-12-01 16:18 UTC, shanenak commented on visualization.py
> +    if len(geo_df_copy['coordinates'][0][0][0]) > 0:
Updated to be slightly more zoomed out. Probably would work better as a formula - note for next time.

2021-12-01 23:35 UTC, shanenak commented on constants.py
> +| Feature Name | Resolution | Source | Updated | Notes |
Yes, added.

2021-12-01 23:37 UTC, shanenak commented on equity_explorer.py
> +from constants import STATES as STATES, EQUITY_DATA_TABLE as EQUITY_DATA_TABLE, TRANSPORT_DATA_TABLE as TRANSPORT_DATA_TABLE, LINKS as LINKS
Yep you are correct. For some reason it was not a fan when I tried that yesterday. Updated!

2021-12-01 23:38 UTC, shanenak commented on queries.py
> +    data.rename({'below_pov_level': 'Below Poverty Level'}, axis=1, inplace=True)
Great, updated.

2021-12-09 19:15 UTC, jstock29 approved these changes
Approving this for final testing in dev. There are some things we'll want to flag for refactoring in the future. The transit geometries also need to be queried so that only the geographically relevant data comes through to the app. Further interface updates can be made in a fresh new branch off of dev going forward.

2021-12-09 19:15 UTC, merged

2021-12-15 19:01 UTC, shanenak commented
Merged with master